javac -cp src src\com\vormetric\pkcs11\sample\Helper.java
javac -cp src src\com\vormetric\pkcs11\sample\CreateKey.java
javac -cp src src\com\vormetric\pkcs11\sample\CreateObject.java
javac -cp src src\com\vormetric\pkcs11\sample\CreateKeypairSignMessage.java
javac -cp src src\com\vormetric\pkcs11\sample\EncryptDecryptFile.java
javac -cp src src\com\vormetric\pkcs11\sample\EncryptDecryptMessage.java
javac -cp src src\com\vormetric\pkcs11\sample\FindDeleteKey.java
javac -cp src src\com\vormetric\pkcs11\sample\FindExportKey.java
javac -cp src src\com\vormetric\pkcs11\sample\EncryptDecryptMetaData.java
javac -cp src src\com\vormetric\pkcs11\sample\EncryptDecryptFileMeta.java
