apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: {{.Values.runlabel}}
  name: crdp-deployment
spec:
  template:
    metadata:
      name: {{.Values.deployment.name}}
      labels:
        run: {{.Values.runlabel}}
    spec:
      containers:
      - image: {{.Values.deployment.crdpimage}}
        name: {{.Values.deployment.crdpimagename}}
        imagePullPolicy: IfNotPresent
        env:
        - name: KEY_MANAGER_HOST
          valueFrom:
            configMapKeyRef:
              name: {{.Values.configuration.configmapname}}
              key: KEY_MANAGER_HOST
        - name: SERVER_MODE
          valueFrom:
            configMapKeyRef:
                name: {{.Values.configuration.configmapname}}
                key: SERVER_MODE
        - name: REGISTRATION_TOKEN
          valueFrom:
            configMapKeyRef:
                name: {{.Values.configuration.configmapname}}
                key: REGISTRATION_TOKEN
        - name: CERT_VALUE
          valueFrom:
            secretKeyRef:
                name: {{.Values.configuration.secretname}}
                key: server.crt
        - name: KEY_VALUE
          valueFrom:
            secretKeyRef:
                name: {{.Values.configuration.secretname}}
                key: server.key
        - name: TRUSTED_CA
          valueFrom:
            secretKeyRef:
                name: {{.Values.configuration.secretname}}
                key: ca.crt

  replicas: {{.Values.replicaCount}}
  selector:
      matchLabels:
        run: {{.Values.runlabel}}

---
apiVersion: v1
data:
  server.crt: {{.Values.configuration.servercrt}}
  ca.crt: {{.Values.configuration.trustedca}}
  server.key: {{.Values.configuration.serverkey}}
kind: Secret
metadata:
  name: {{.Values.configuration.secretname}}
type: Opaque
---

apiVersion: v1
items:
- apiVersion: v1
  data:
    SERVER_MODE: {{.Values.configuration.servermode | quote}}
    KEY_MANAGER_HOST: {{.Values.configuration.kms}}
    REGISTRATION_TOKEN:  {{.Values.configuration.rtoken}}
  kind: ConfigMap
  metadata:
    name: {{.Values.configuration.configmapname}}
kind: List
metadata: