apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: devadv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: localhost:30001/react-app:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: devadv
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002  # Expose React app on port 30002
  selector:
    app: react-app