version: '3.8'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    environment:
      GITLAB_ROOT_PASSWORD: "ChangeIt01!"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    shm_size: '2g'
    networks:
      - ci-cd-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/users/sign_in"]
      interval: 10s
      timeout: 5s
      retries: 60

  docker-dind:
    image: docker:dind
    container_name: docker-dind
    privileged: true
    volumes:
      - docker-data:/var/lib/docker
      - ./certs:/certs
      - ./certs/registry_5000:/certs/registry_5000
      - dind-storage:/var/lib/docker
    environment:
      - DOCKER_TLS_CERTDIR=
    networks:
      - ci-cd-network
    restart: unless-stopped
    entrypoint: >
      sh -c "
        mkdir -p /etc/docker/certs.d/registry:5000 &&
        cp /certs/registry_5000/ca.crt /etc/docker/certs.d/registry:5000/ca.crt &&
        dockerd-entrypoint.sh
      "

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: custom_jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/data:/var/jenkins_home
      - ./certs:/certs
      #- /var/run/docker.sock:/var/run/docker.sock
      #- //var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://docker-dind:2375
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/casc.yaml
      - JAVA_OPTS=-Xmx1024m -Djenkins.install.runSetupWizard=false
      - GITLAB_ROOT_PASSWORD=ChangeIt01!
      - GITLAB_PERSONAL_ACCESS_TOKEN=${GITLAB_PERSONAL_ACCESS_TOKEN}
      - API_SERVER_IP=${API_SERVER_IP}
    command: >
      bash -c "
        chown -R jenkins:jenkins /var/jenkins_home &&
        gosu jenkins /usr/local/bin/jenkins.sh
      "
    depends_on:
      gitlab:
        condition: service_healthy
      docker-dind:
        condition: service_started
      registry:
        condition: service_started
    networks:
      - ci-cd-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 10s
      timeout: 5s
      retries: 30
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      - ./certs:/certs
      - ./registry/data:/var/lib/registry
    networks:
      - ci-cd-network

volumes:
  dind-storage:

networks:
  ci-cd-network:
    driver: bridge