jenkins:
  systemMessage: "Automated Jenkins Setup"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "ChangeIt01!"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: >
      pipelineJob('Deploy_Sample_App_ADP') {
        parameters {
          stringParam("GIT_REPO_UI", "http://gitlab:80/ciphertrust/crestline-ui.git", "URL of the Crestline UI Git repository")
          stringParam("GIT_REPO_API", "http://gitlab:80/ciphertrust/crestline-api.git", "URL of the Crestline API Git repository")
          stringParam("GIT_REPO_DEP", "http://gitlab:80/ciphertrust/crestline-deployment.git", "URL of the Crestline Deployment Git repository")
          stringParam("DOCKER_REGISTRY", "registry:5000", "URL of the Docker registry")
          stringParam("API_SERVER_IP", "192.168.2.221", "URL of the API Server")
          stringParam("DATASOURCE_URL", "jdbc:postgresql://postgres-service.app-stack.svc.cluster.local:5432/cdsp", "Connection string for DB")
          stringParam("DATASOURCE_USERNAME", "postgres", "Username for the DB")
          stringParam("DATASOURCE_PASSWORD", "ChangeIt01!", "Password for the DB")
        }
        definition {
          cpsScm {
            scm {
              git {
                remote { 
                  url('http://gitlab:80/ciphertrust/crestline-deployment.git')
                  credentials('gitlab-credentials')
                }
                branch('main')
              }
            }
            scriptPath('Jenkinsfile')
            lightweight(true)
          }
        }
        triggers {
          gitlabPush {
            buildOnPushEvents(true)
            buildOnMergeRequestEvents(false)
            enableCiSkip(false)
            setBuildDescription(true)
          }
        }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: gitlab-credentials
              username: root
              password: "ChangeIt01!"